# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: en

timezone: Asia/Jakarta

# jekyll-seo-tag settings
title: Abdul Hakim
tagline: Cloud | DevOps | AI Notes

description: >-
  Abdul Hakim's personal blog about Cloud, DevOps, SRE, Linux and AI.

url: "https://ahakimx.id"

github:
  username: ahakimx

social:
  name: Abdul Hakim
  links:
    - https://github.com/ahakimx
    - https://twitter.com/a_hakimx
    - https://linkedin.com/in/ahakimx

# Web Analytics Settings
analytics:
  cloudflare:
    id: 7d0e5f68f6764daba503db40ced6e3cd

theme_mode: # [light | dark]

webmaster_verifications:
  google: kwyA2jqdgjISfJvWYQ8EOBjgU9PRXYBom2Lhfi5qApQ

avatar: "https://github.com/ahakimx.png"
toc: true

comments:
  provider: disqus
  disqus:
    shortname: ahakimx

paginate: 10

baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

include:
  - admin

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
